// Compiles DTCG-style token JSON into CSS custom properties.
//
//   src/shared.json  -> :root                       (radius, font, border, motion)
//   src/light.json   -> :root, [data-theme="light"] (color, light mode)
//   src/dark.json    -> [data-theme="dark"]         (color, dark mode)
//                       + system dark fallback when no data-theme is set
//
// Token names: group path joined with "-", prefixed with "--eui-".
//   color.accent-fg -> --eui-color-accent-fg
// Aliases: "{color.accent}" becomes "var(--eui-color-accent)".

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(here, "..", "src");
const outDir = path.join(here, "..", "dist");

function load(name) {
  return JSON.parse(readFileSync(path.join(srcDir, name), "utf8"));
}

function flatten(tree, prefix = []) {
  const out = [];
  for (const [key, node] of Object.entries(tree)) {
    if (key.startsWith("$")) continue;
    if (node && typeof node === "object" && "$value" in node) {
      out.push({ path: [...prefix, key], value: node.$value });
    } else if (node && typeof node === "object") {
      out.push(...flatten(node, [...prefix, key]));
    }
  }
  return out;
}

function toVarName(parts) {
  return `--eui-${parts.join("-")}`;
}

function resolveAliases(value) {
  return value.replace(/\{([a-z0-9.-]+)\}/gi, (_, ref) => {
    return `var(${toVarName(ref.split("."))})`;
  });
}

function declarations(tokens) {
  return flatten(tokens)
    .map(({ path: p, value }) => `  ${toVarName(p)}: ${resolveAliases(String(value))};`)
    .join("\n");
}

const header = `/* Generated by packages/tokens/scripts/build.mjs. Do not edit by hand. */\n`;

const shared = load("shared.json");
const light = load("light.json");
const dark = load("dark.json");

const css = [
  header,
  `:root {\n${declarations(shared)}\n${declarations(light)}\n  color-scheme: light;\n}\n`,
  `[data-theme="light"] {\n${declarations(light)}\n  color-scheme: light;\n}\n`,
  `[data-theme="dark"] {\n${declarations(dark)}\n  color-scheme: dark;\n}\n`,
  `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${declarations(dark)
    .split("\n")
    .map((l) => "  " + l)
    .join("\n")}\n    color-scheme: dark;\n  }\n}\n`,
].join("\n");

mkdirSync(outDir, { recursive: true });
writeFileSync(path.join(outDir, "tokens.css"), css);
console.log(`tokens: wrote ${path.join("dist", "tokens.css")} (${css.length} bytes)`);
